#SpringApplication will load properties from application.properties files in the following
#locations and add them to the Spring Environment:
#1. A /config subdirectory of the current directory.
#2. The current directory
#3. A classpath /config package
#4. The classpath root
spring:
#不显示banner
  main:
    banner-mode: "off"
#    加载application-dev.yml配置文件
  profiles:
    active: dev
#国际化和thymeleaf可以在MvcConfig中配置
#    缓存模板 @see ThymeleafAutoConfiguration
  thymeleaf:
    cache: false
    #国际化
  messages:
    basename: messages/message

#    banner 路径
banner:
  location: banner.txt
#  HTTP端口
server:
  port: 8888
#  ssl:
#    key-store: classpath:tomcat.jks
#    key-store-password: 123456
#    key-password: 123456