spring:
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/etvdb_test?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
config:
  #类型转换配置
  dataTypes: classpath:/datatype.yml
  #构造配置
  generator: classpath:/generator.yml
  #表前缀
  tablePre: pt_